# Generated by Django 3.2.13 on 2022-04-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0003_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='roomForLineup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='creative_project.room'),
        ),
    ]
