# Generated by Django 3.2.13 on 2022-04-24 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0008_lineup_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 0, 8, 3, 993476)),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='winstreak',
            field=models.IntegerField(default=0),
        ),
    ]
