# Generated by Django 3.2.13 on 2022-04-24 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0011_alter_extendeduser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 20, 4, 34, 510285)),
        ),
    ]
