# Generated by Django 4.0.4 on 2022-04-25 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0013_extendeduser_totalwins_lineup_dingers_lineup_hits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 25, 20, 22, 5, 246758)),
        ),
    ]
