# Generated by Django 3.2.13 on 2022-04-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0002_auto_20220421_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
