# Generated by Django 3.2.13 on 2022-04-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0007_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
