# Generated by Django 3.2.13 on 2022-04-24 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0009_auto_20220424_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 14, 26, 9, 787957)),
        ),
    ]
