# Generated by Django 3.2.13 on 2022-04-24 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0010_auto_20220424_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 17, 59, 13, 549485)),
        ),
    ]
