# Generated by Django 4.0.4 on 2022-04-25 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_project', '0012_auto_20220424_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='totalWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='dingers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='strikeouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 25, 18, 44, 57, 840258)),
        ),
    ]
